//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektObiektowe
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tuition_fees
    {
        public int payment_id { get; set; }
        public int student_id { get; set; }
        public decimal fee_amount { get; set; }
        public System.DateTime date_of_payment { get; set; }
    
        public virtual student student { get; set; }
    }
}
